### PR TITLE
test Flux master [Do Not Merge]

### PR DESCRIPTION
**Pull request by IanButterworth**

### CODE REVIEW

**Comment by IanButterworth** [comment]
@DhairyaLGandhi looks like a breakage. I guess this was use of a Flux internal? 
https://github.com/r3tex/ObjectDetector.jl/pull/55/checks?check_run_id=2058891997#step:5:166

**Comment by DhairyaLGandhi** [comment]
I think if you added the affine and tracked_stats fields, that would help.

**Comment by DhairyaLGandhi** [comment]
Not really an internal, since we expect it to work.

**Comment by CarloLucibello** [comment]
this should be fixed by https://github.com/FluxML/Flux.jl/pull/1538

**Comment by IanButterworth** [comment]
Looks good @CarloLucibello @DhairyaLGandhi 

In case it's not obvious, this PR tests https://github.com/FluxML/Flux.jl/pull/1538

**Comment by CarloLucibello** [comment]
Could check running the benchmark that there are no perf regressions? I get cuda out of memory errors on both v0.12 and v0.11

**Comment by IanButterworth** [comment]
Sorry for the delay. I don't have access to a GPU, so this is CPU-only

Julia 1.6 in both.

## Flux master 0.12.0
```julia
julia> using ObjectDetector, BenchmarkTools

julia> yolomod = YOLO.v3_608_COCO(batch=1, silent=true);

julia> batch = emptybatch(yolomod);

julia> size(batch)
(416, 416, 3, 1)

julia> @btime res = yolomod(batch, detectThresh=0.5, overlapThresh=0.8);
  1.006 s (20340 allocations: 3.58 GiB)

julia> yolomod = YOLO.v3_608_COCO(batch=9, silent=true);

julia> batch = emptybatch(yolomod);

julia> size(batch)
(416, 416, 3, 9)

julia> @btime res = yolomod(batch, detectThresh=0.5, overlapThresh=0.8);
  7.614 s (106010 allocations: 8.87 GiB)
```

## Flux 0.11.6
```julia
julia> using ObjectDetector, BenchmarkTools

julia> yolomod = YOLO.v3_608_COCO(batch=1, silent=true);

julia> batch = emptybatch(yolomod);

julia> size(batch)
(416, 416, 3, 1)

julia> @btime res = yolomod(batch, detectThresh=0.5, overlapThresh=0.8);
  1.087 s (18897 allocations: 3.73 GiB)

julia> yolomod = YOLO.v3_608_COCO(batch=9, silent=true);

julia> batch = emptybatch(yolomod);

julia> size(batch)
(416, 416, 3, 9)

julia> @btime res = yolomod(batch, detectThresh=0.5, overlapThresh=0.8);
  8.350 s (104571 allocations: 10.16 GiB)
```

**Comment by CarloLucibello** [comment]
Looks good! Gpu side shouldn't be any change, and in any case nothing we
can control being related to CUDA.jl

Il sab 27 mar 2021, 17:36 Ian Butterworth ***@***.***> ha
scritto:

**Comment by IanButterworth** [comment]
Great! Will the 0.12 release be made soon?

**Comment by CarloLucibello** [comment]
I'll push to have a release tomorrow

**Comment by IanButterworth** [comment]
Nice!

**Pull request closed without merging**
